
subgroup_to_group: "config_subgroups/subgroup_to_group.json"

subgroup_phages: "config_subgroups/subgroup_phages.json"

nonsyntenic_groups: "config/nonsyntenic_groups.json"

groups_to_process: "config/groups_to_process.json"